# Model Trainer

In [11]:
### Import Data and requred packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR 
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import RandomizedSearchCV
# from catboost import CatboostRegressor
# from xgboost import XGBRegressor
import warnings

In [12]:
df = pd.read_csv('C:/Users/ocema/OneDrive/Desktop/DS_projects/notebooks/data/stud.csv')
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [14]:
df['average'] = round((df['math_score'] + df['reading_score'] + df['writing_score'])/3, 2)
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33

In [15]:
x = df.drop(columns=('average'), axis=1)
y = df['average']

In [17]:
# Create column transformer with  3 types of transformers
num_features = x.select_dtypes(exclude='object').columns
cat_features = x.select_dtypes(include='object').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

num_transformer = StandardScaler()
one_hot_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder', one_hot_transformer, cat_features),
        ('StandardScaler', num_transformer, num_features)
    ]
)

In [18]:
x = preprocessor.fit_transform(x)
x.shape

(1000, 20)

In [19]:
# Train, test, split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
x_train.shape, x_test.shape

((800, 20), (200, 20))

### Create a function to evaluate the performance of each model after training

In [20]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [21]:
models = {
    'LinearRegression': LinearRegression(),
    'Lasso': Lasso(),
    'Ridge': Ridge(),
    'KNeighbors Regressor': KNeighborsRegressor(),
    'Decision Tree': DecisionTreeRegressor(),
    'Random Forest': RandomForestRegressor(),
    'AdaBoost Regressor': AdaBoostRegressor(),
}


model_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train)  # train each model
    
    # make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    
    #Evaluate, train and test models
    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)
    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for training set')
    print(f'Root Mean Squared Error: {model_train_rmse}')
    print(f'Mean Absolute Error: {model_train_mae}')
    print(f'R2 Score: {model_train_r2}')
    print('===============================================')
    
    print('Model performance for test set')
    
    print(f'Root Mean Squared Error: {model_test_rmse}')
    print(f'Mean Absolute Error: {model_test_mae}')
    print(f'R2 Score: {model_test_r2}')
    
    r2_list.append(model_test_r2)
    
    
    print('=' * 30)
    print('\n')

LinearRegression
Model performance for training set
Root Mean Squared Error: 0.0027007464196733702
Mean Absolute Error: 0.0023088484644901365
R2 Score: 0.9999999634289128
===============================================
Model performance for test set
Root Mean Squared Error: 0.0026485389536514254
Mean Absolute Error: 0.0021580978274355544
R2 Score: 0.9999999672773194
==============================


Lasso
Model performance for training set
Root Mean Squared Error: 1.064499921044892
Mean Absolute Error: 0.8504957189732995
R2 Score: 0.9943185195009098
===============================================
Model performance for test set
Root Mean Squared Error: 1.1143067990100022
Mean Absolute Error: 0.8769183237190569
R2 Score: 0.9942077712680123
==============================


Ridge
Model performance for training set
Root Mean Squared Error: 0.008465551802445098
Mean Absolute Error: 0.006829166823374262
R2 Score: 0.999999640680492
===============================================
Model performance for test set
Root Mean Squared Error: 0.00935647022265365
Mean Absolute Error: 0.007314586177989178
R2 Score: 0.9999995916239893
==============================


KNeighbors Regressor
Model performance for training set
Root Mean Squared Error: 2.25746340280413
Mean Absolute Error: 1.7682475
R2 Score: 0.9744487771324665
===============================================
Model performance for test set
Root Mean Squared Error: 3.0706489509548303
Mean Absolute Error: 2.28337
R2 Score: 0.9560158219315538
==============================


Decision Tree
Model performance for training set
Root Mean Squared Error: 7.53644380168212e-16
Mean Absolute Error: 7.993605777301127e-17
R2 Score: 1.0
===============================================
Model performance for test set
Root Mean Squared Error: 1.6006606448588656
Mean Absolute Error: 1.10655
R2 Score: 0.988048162572904
==============================


Random Forest
Model performance for training set
Root Mean Squared Error: 0.29463587033404354
Mean Absolute Error: 0.1821101249999991
R2 Score: 0.9995647472830914
===============================================
Model performance for test set
Root Mean Squared Error: 1.1435555731576834
Mean Absolute Error: 0.5222069999999996
R2 Score: 0.9938997070356065
==============================


AdaBoost Regressor
Model performance for training set
Root Mean Squared Error: 1.7125559271511954
Mean Absolute Error: 1.3446538964800536
R2 Score: 0.9852951777342315
===============================================
Model performance for test set
Root Mean Squared Error: 2.121074637834795
Mean Absolute Error: 1.5179718458292775
R2 Score: 0.9790131119991466
==============================